export const CREATE_STUDENT = "CREATE_STUDENT";
export const LOAD_STUDENTS_SUCCESS = "LOAD_STUDENTS_SUCCESS";
export const LOAD_DEPTS_SUCCESS = "LOAD_DEPTS_SUCCESS";
export const CREATE_STUDENT_SUCCESS = "CREATE_STUDENT_SUCCESS";
export const UPDATE_STUDENT_SUCCESS = "UPDATE_STUDENT_SUCCESS";
export const BEGIN_API_CALL = "BEGIN_API_CALL";
export const API_CALL_ERROR = "API_CALL_ERROR";

export const DELETE_STUDENT_OPTIMISTIC = "DELETE_STUDENT_OPTIMISTIC";
export const SEARCH_STUDENT_SUCCESS = "SEARCH_STUDENT_SUCCESS";